# Generated by Django 5.1.2 on 2024-10-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_shop_id_6c5838_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_discoun_0fa1d1_idx',
        ),
    ]
