version: '3.8'

services:
  web1:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=items.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase

  web2:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=items.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase

  web3:
    build: .
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=items.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_replica:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase_replica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - secondary_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web1
      - web2
      - web3
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  postgres_data:
  secondary_postgres_data:
