# Generated by Django 4.2.6 on 2024-09-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='blog_tag_name_43b6ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='blog_user_usernam_41432c_idx',
        ),
    ]
